# Name des Programmes.
APPLICATION = timer-example

# RIOT-Label für das Microkontroller-Board.
BOARD ?= adafruit-feather-nrf52840-sense

# Pfad zum RIOT Betriebssystem im lokalen Dateienverzeichnis.
RIOTBASE ?= $(CURDIR)/../RIOT

# Benötigte Timer Module.
USEMODULE += ztimer
USEMODULE += ztimer_sec

include $(RIOTBASE)/Makefile.include
