# Name des Programmes.
APPLICATION = hello-world

# RIOT-Label für das Microkontroller-Board.
BOARD ?= adafruit-feather-nrf52840-sense

# Pfad zum RIOT Betriebssystem im lokalen Dateienverzeichnis.
RIOTBASE ?= $(CURDIR)/../RIOT

include $(RIOTBASE)/Makefile.include
