# Name des Programmes.
APPLICATION = shell

# RIOT-Label für das Microkontroller-Board.
BOARD ?= adafruit-feather-nrf52840-sense

# Pfad zum RIOT Betriebssystem im lokalen Dateienverzeichnis.
RIOTBASE ?= $(CURDIR)/../RIOT

# Inkludiere das shell modul.
USEMODULE += shell

include $(RIOTBASE)/Makefile.include
