# Name des Programmes.
APPLICATION = saul_example

# RIOT-Label für das Microkontroller-Board.
BOARD ?= adafruit-feather-nrf52840-sense

# Pfad zum RIOT Betriebssystem im lokalen Dateienverzeichnis.
RIOTBASE ?= $(CURDIR)/../RIOT

# Benötigte SAUL Module.
USEMODULE += saul
USEMODULE += saul_default

# Benötigte Timer Module.
USEMODULE += ztimer
USEMODULE += ztimer_msec

include $(RIOTBASE)/Makefile.include
